In [1]:
import akshare
import awkward as ak
import os

In [2]:
df_tencent = akshare.stock_hk_hist(symbol="00700", period="daily", start_date="20120101", end_date="20121231", adjust='qfq')
df_tencent

,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2012-01-03,21.820,21.820,22.014,21.587,2345274,371451904.0,2.01,2.65,0.563,0.13
1,2012-01-04,22.014,21.781,22.014,21.626,1854080,293925728.0,1.78,-0.18,-0.039,0.10
2,2012-01-05,21.820,21.510,21.976,21.393,3162115,499747872.0,2.68,-1.24,-0.271,0.17
3,2012-01-06,20.966,20.947,21.529,20.830,3034822,470292992.0,3.25,-2.62,-0.563,0.16
4,2012-01-09,20.850,21.083,21.219,20.131,2818144,432456960.0,5.19,0.65,0.136,0.15
...,...,...,...,...,...,...,...,...,...,...,...
242,2012-12-21,39.048,39.204,39.281,38.776,2856522,704141760.0,1.28,-0.59,-0.232,0.15
243,2012-12-24,39.669,38.932,39.669,38.699,958581,236292736.0,2.47,-0.69,-0.272,0.05
244,2012-12-27,39.631,39.165,39.631,38.854,2779211,686690368.0,2.00,0.60,0.233,0.15
245,2012-12-28,39.825,39.631,39.864,39.087,2224786,554373056.0,1.98,1.19,0.466,0.12
246,2012-12-31,39.631,39.436,39.708,39.165,1317565,328709504.0,1.37,-0.49,-0.195,0.07

In [3]:
df_tencent = df_tencent.rename(columns={'日期':'Date', '开盘': 'Open', '收盘': 'Close', '最高': 'High', '最低': 'Low', '成交量': 'Volume'})
df_tencent=df_tencent.loc[:, ['Date', 'Open', 'High', 'Low', 'Close', 'Volume']]

In [4]:
if not os.path.exists('./data/'):
    os.makedirs('./data')
with open('./data/test_stock.txt', 'w', encoding='utf-8') as f:
    df_tencent.to_csv(f, index=False)